const FLIGHT_ACTIONS = {
    FETCH_ALL_FLIGHTS_PENDING: "FETCH_ALL_FLIGHTS_PENDING",
    FETCH_ALL_FLIGHTS_RESOLVE: "FETCH_ALL_FLIGHTS_RESOLVE",
    FETCH_ALL_FLIGHTS_REJECT: "FETCH_ALL_FLIGHTS_REJECT",

    SEARCH_FLIGHT_PENDING: "SEARCH_FLIGHT_PENDING",
    SEARCH_FLIGHT_RESOLVE: "SEARCH_FLIGHT_RESOLVE",
    SEARCH_FLIGHT_REJECT: "SEARCH_FLIGHT_REJECT",

    ADD_FLIGHT_PENDING: "ADD_FLIGHT_PENDING",
    ADD_FLIGHT_RESOLVE: "ADD_FLIGHT_RESOLVE",
    ADD_FLIGHT_REJECT: "ADD_FLIGHT_REJECT"
};

export default FLIGHT_ACTIONS;
